### ISSUE TITLE
[Feature Request] Add option for spell slot display style

### ISSUE THREAD

**Issue by nschoenwald** [eastcw/foundryvtt-compactBeyond5eSheet#12]
First of all, thank you so much for the spell slot check boxes!

I personally don't need to have both the check boxes and the numeric fields. I think it would be ideal to have a spell slot display style setting with three choices in the module settings.
- Check Boxes and Numeric (default)
- Check Boxes only
- Numeric only

**Comment by eastcw** [comment]
Thanks for this suggestion, I really appreciate knowing how people use the sheet, and what they want it to do. I did consider this idea when adding the check boxes, but my thinking was as follows:

1. Even with the character sheet at minimum width there is room for both the numerical display and the check-box display for 8 spell slots at each level. This is more than enough for high level spellcasting characters without getting cluttered in my opinion
2. If I hide the numerical display, it's no longer possible to edit the maximum number of spell slots - not a feature that needs using very often, but I'd rather not take a step backward in functonality if I can avoid it. This is especially true since not all users would have removed that functionality, leading to potential situations where people are confused about what they can and can't do with the character sheet, and what settings they need to change to do so

For these reasons, I will not be implementing this at the moment.

**Comment by nschoenwald** [comment]
Thanks for the response -- it's definitely not a big deal, so no harm not implementing this for the time being. I really appreciate you maintaining and improving this module, thanks again!
